analytics: {}
color:
  brandColors:
    - '#13293d'
    - '#e8f1f2'
    - '#26a09a'
    - '#006494'
    - '#6fbeeb'
  brandStrength: 0.334918
  lightness: 0.661684
  rhythmicContrast: 0.5
  saturation: 0.502038
cta: {}
layout_spectrum: 0.277173
name: Cifras
opengraph: {}
purpose:
  - name: stars
typography_spectrum: 0.432066
