layout_spectrum: 0.662224959814921
typography_spectrum: 0.682265154318884
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.7936677471734583
  lightness: 0.8307291439268738
  saturation: 0.08180790161713958
  rhythmicContrast: 0.1252567667979747
coverPrefs:
  filter: false
name: Cifras
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
