name: Cifras
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13293d'
    - '#e8f1f2'
    - '#26a09a'
    - '#006494'
    - '#6fbeeb'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 1
purpose:
  - name: stars
    item: null
    url: null
